config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  #mount Sidekiq::Web => '/sidekiq'

  root 'pages#home'

  resources :campaigns, except: [:new] do
    post 'raffle', on: :member
  end
  get 'members/:token/opened', to: 'members#opened'
  resources :members, only: [:create, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  after_validation :set_member, on: :create
  before_validation :set_status, on: :create

  belongs_to :user
  has_many :members, dependent: :destroy
  
  enum status: [:pending, :finished]
  validates :title, :description, :user, :status, presence: true

  def count_opened
    self.members.where(open: true).count
  end

  private

    def set_status
      self.status = :pending
    end

    def set_member
      self.members << Member.create(name: self.user.name, email: self.user.email)
    end
end

app/models/member.rb
class Member < ApplicationRecord
  validates :name, :email, :campaign, presence: true
  belongs_to :campaign
  after_destroy :set_campaign_pending

  def set_pixel
    self.open = false
    self.token = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless Member.exists?(token: random_token)
    end
    self.save!
  end

  protected

    def set_campaign_pending
      self.campaign.update(status: :pending)
    end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :campaigns, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound, :with => :render_404

  def render_404
    redirect_to main_app.root_url
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_campaign, only: [:show, :destroy, :update, :raffle]
  before_action :is_owner?, only: [:show, :destroy, :update, :raffle]

  def index
    @campaigns = current_user.campaigns
  end

  def create
    @campaign = Campaign.new(user: current_user, title: 'Nova Campanha', description: 'Descreva sua campanha...')

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to "/campaigns/#{@campaign.id}" }
      else
        format.html { redirect_to main_app.root_url, notice: @campaign.errors }
      end
    end
  end

  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.json { render json: true }
      else
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @campaign.destroy

    respond_to do |format|
      format.json { render json: true }
    end
  end

  def raffle
    respond_to do |format|
      if @campaign.status != "pending"
        format.json { render json: 'Já foi sorteada', status: :unprocessable_entity }
      elsif @campaign.members.count < 3
        format.json { render json: 'A campanha precisa de pelo menos 3 pessoas', status: :unprocessable_entity }
      else
        CampaignRaffleJob.perform_later @campaign
        format.json { render json: true }
      end
    end
  end

  private

  def set_campaign
    @campaign = Campaign.find(params[:id])
  end

  def campaign_params
    params.require(:campaign).permit(:title, :description, :event_date, :event_hour, :location).merge(user: current_user)
  end

  def is_owner?
    unless current_user == @campaign.user
      respond_to do |format|
        format.json { render json: false, status: :forbidden }
        format.html { redirect_to main_app.root_url }
      end
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!, except: [:opened]

  before_action :set_member, only: [:show, :destroy, :update]
  before_action :is_owner?, only: [:destroy, :update]
  before_action :set_member_by_token, only: [:opened]

  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.json { render json: @member }
      else
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @member.destroy

    respond_to do |format|
      format.json { render json: true }
    end
  end

  def update
    respond_to do |format|
      if @member.update(member_params)
        format.json { render json: true }
      else
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  def opened
    @member.update(open: true)
    gif = Base64.decode64("R0lGODlhAQABAPAAAAAAAAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==")
    render text: gif, type: 'image/gif'
  end

  private

  def set_member
    @member = Member.find(params[:id])
  end

  def set_member_by_token
    @member = Member.find_by!(token: params[:token])
  end

  def member_params
    params.require(:member).permit(:name, :email, :campaign_id)
  end

  def is_owner?
    unless current_user == @member.campaign.user
      respond_to do |format|
        format.json { render json: false, status: :forbidden }
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if user_signed_in?
      @campaigns = current_user.campaigns
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
  def open_number(campaign)
    "#{campaign.count_opened}/#{campaign.members.count}"
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/campaigns/index.html.erb
<div class="row campaigns">
  <div class="col s8 offset-s2">
    <p class="title">Campanhas</p>
  </div>

  <div class="row cards">
    <div class="col s8 offset-s2">
      <%= render 'shared/campaigns', campaigns: @campaigns %>
    </div>
  </div>

  <div class="fixed-action-btn campaigns-btn">
    <%= form_tag("/campaigns", method: "post") do %>
      <button class="btn-floating btn-large red pulse" type="submit">
        <i class="large material-icons">add</i>
      </button>
    <% end %>
  </div>
</div>

app/views/campaigns/show.html.erb
<div class="row campaigns">
  <div class="col s8 offset-s2">
    <p class="title">Informações</p>
  </div>

  <div class="campaign">
    <div class="row cards">
      <div class="col s8 offset-s2">
        <div class="card horizontal">
          <div class="card-content col s12">
            <%= form_for @campaign, url: {action: "update"}, html: {class: "col s12 update_campaign"} do |f| %>
              <div class="row">
                <div class="row">
                  <div class="col s12 l4 input-field">
                    <%= f.text_field :title, 'data-length': "20" %>
                    <label for="title" class="<%= (@campaign.title)? 'active' : '' %>">Título</label>
                  </div>
                  <div class="col s12 l3 input-field">
                    <%= f.date_field :event_date, class: 'datepicker' %>
                    <label for="title" class="<%= (@campaign.event_date)? 'active' : '' %>">Data</label>
                  </div>
                  <div class="col s12 l2 input-field">
                    <%= f.text_field :event_hour %>
                    <label for="title" class="<%= (@campaign.event_hour)? 'active' : '' %>">Hora</label>
                  </div>
                  <div class="col s12 l3 input-field">
                    <%= f.text_field :location, 'data-length': "20" %>
                    <label for="title" class="<%= (@campaign.location)? 'active' : '' %>">Local</label>
                  </div>
                </div>
                <div class="row">
                  <div class="col s12 input-field">
                    <%= f.text_field :description, 'data-length': "150" %>
                    <label for="title" class="<%= (@campaign.description)? 'active' : '' %>">Descrição</label>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="col s8 offset-s2">
      <p class="title">Membros</p>
    </div>

    <div class="row cards members">
      <div class="col s8 offset-s2">
        <div class="card horizontal">
          <div class="card-content col s12">

          <div class="member_list">
            <% @campaign.members.each do |m| %>
              <div class="member" id="member_<%= m.id %>">
                <div class="row">
                  <%= form_for m do |f| %>
                    <div class="col s12 m5 input-field">
                      <%= f.text_field :name, id: "name_member_#{m.id}", 'data-id': m.id, class: "validate member_update" %>
                      <label for="name_member_#{m.id}" class="active">Nome</label>
                    </div>
                    <div class="col s12 m5 input-field">
                      <%= f.email_field :email, id: "email_member_#{m.id}", 'data-id': m.id, class: "validate member_update" %>
                      <label for="email_member_#{m.id}" class="active" data-error="Formato incorreto">Email</label>
                    </div>
                  <% end %>

                  <div class="col s3 offset-s3 m1 input-field">
                    <i class="material-icons icon <%= (m.open)? 'opened' : '' %>">visibility</i>
                  </div>
                  <div class="col s3 m1 input-field">
                    <a href="#" class="remove_member" id="<%= m.id %>">
                      <i class="material-icons icon">delete</i>
                    </a>
                  </div>
                </div>
              </div>
            <% end %>
          </div>

          <%= form_for(Member.new) do |f| %>
            <div class="member">
              <div class="row">
                <%= f.hidden_field :campaign_id, value: @campaign.id %>
                <div class="col s12 m5 input-field">
                  <%= f.text_field :name, class: "validate"%>
                  <label for="name" class="active">Nome</label>
                </div>
                <div class="col s12 m5 input-field">
                  <%= f.email_field :email, class: "validate" %>
                  <label for="member[email]" class="active" data-error="Formato incorreto">Email</label>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row btn-actions">
    <div class="col s12 center">
      <div class="col s6 m3 offset-m3 l2 offset-l4">
      <!--
        <%#= form_for @campaign, method: 'delete', html: {class: 'remove_campaign'} do |f| %>
          <button type='submit' class="waves-effect waves-light btn grey">Remover</button>
        <%# end %>
      -->
        <button data-target="confirmation-modal" class="btn modal-trigger btn grey">Remover</button>
      </div>
      <div class="col s6 m3 l3">
        <%= form_tag(raffle_campaign_path(@campaign), method: 'post', class: 'raffle_campaign') do %>
          <button type='submit' class="waves-effect waves-light btn red">Sortear e enviar</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div id="confirmation-modal" class="modal">
  <div class="modal-content">
    <h5>Remover Campanha</h5>
    <p>Deseja realmente excluir essa campanha?</p>
  </div>
  <div class="modal-footer">
    <p class="modal-action modal-close waves-effect waves-red btn-flat">Cancelar</p>
    <p id="remove-campaign" class="modal-action modal-close waves-effect waves-red btn-flat">Remover</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NossoAmigoSecreto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag %>
  </head>

  <body>
    <header>
      <%= render "shared/navbar" %>
    </header>

    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <footer>
      <%= render "shared/footer" %>
    </footer>
  </body>
</html>

app/views/layouts/old_mailer_1517473163.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      /* Email styles need to be inline */
    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="row home">
  <div class="center">

    <h4  class="title">Surpreenda no Amigo Secreto</h4>
    <h5 class="subtitle">Crie a sua brincadeira apenas com o nome e email dos seus amigos</h5>
    <h5 class="subtitle2">Rápido, fácil e garantido <i class="material-icons home-icon">favorite</i></h5>
    
    <%= form_tag("/campaigns", method: "post") do %>
      <%= submit_tag("Criar Agora", class: "waves-effect waves-light btn home-button") %>
    <% end %>

    <% if !@campaigns.nil? %>
      <h5 class="title my-campaigns-title">Suas campanhas</h5>
    <% end %>
    <%= render 'shared/campaigns', campaigns: @campaigns %>
    
  </div>
</div>

app/views/shared/_campaigns.html.erb
<% campaigns.each do |c| %>
  <div class="card horizontal">
    <div class="card-content col s12">
      <div class="col s12 l8 m12">
        <div class="row">
          <div class="col s8 m9 l9">
            <p class="title"><%= truncate(c.title, length: 30, omission: '...') %></p>
          </div>
          <div class="col s4 m2 l2">
            <p class="data"><%= (c.event_date)? c.event_date.strftime("%d/%m/%y") : '' %></p>
          </div>
        </div>
        <div class="row">
          <div class="col s12 m12 l12">
            <p class="subtitle"><%= truncate(c.description, length: 70, omission: '...') %></p>
          </div>
        </div>
        <div class="row status">
          <div class="col s6 m6 l4 visibility">
            <i class="material-icons visibility-icon">visibility</i>
            <span class="visibility-text">Vistos <%= open_number(c) %></span>
          </div>
          <div class="col s2 m2 offset-s4 l2 offset-l6">
            <span class="new badge <%= (c.status == "pending")? 'orange' : '' %>"> <%= (c.status == "pending")? 'Pendente' : 'Sorteado' %> </span>
          </div>
        </div>
      </div>
      <div class="col l4 s12 m12 center enter">
        <div class="row">
          <div class="col s12">
            <a class="waves-effect waves-light btn grey" href=<%= "/campaigns/#{c.id}" %>>Entrar</a>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end unless campaigns.nil? %>

app/views/shared/_footer.html.erb
<div class="page-footer">
  <div class="container">
    <div class="copyright">
      <b>Criado com
        <i class="material-icons copyright-icon">favorite</i>
        no
        <a class="copyright-link" href="http://onebitcode.com/bootcamp-one-bit-code/"> Bootcamp OneBitCode</a>
      </b>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-fixed">
  <nav class="top-nav">
    <div class="nav-wrapper col s12">
      <a href="/" class="brand-logo">
        <%= image_tag("logo.png", class: "logo-img") %>
        <span class="logo-title">
          Nosso Amigo Secreto
        </span>
      </a>

      <a href="#" data-activates="side-bar" class="button-collapse"><i class="material-icons">menu</i></a>

      <ul class="right hide-on-med-and-down">
        <% if current_user %>
          <li><a href="/campaigns">Campanhas</a></li>
          <li><a href="/users/edit">Perfil</a></li>
          <li>  <%= link_to('Sair', destroy_user_session_path, :method => :delete) %></li>
        <% else %>
          <li><a href="/users/sign_in">Entrar</a></li>
          <li><a href="/users/sign_up">Criar Conta</a></li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

<ul class="side-nav" id="side-bar">
  <% if current_user %>
    <li><a href="/campaigns">Campanhas</a></li>
    <li><a href="/users/edit">Perfil</a></li>
    <li><div class="divider"></div></li>
    <li><%= link_to('Sair', destroy_user_session_path, :method => :delete) %></li>
  <% else %>
    <li><a href="/users/sign_in">Entrar</a></li>
    <li><div class="divider"></div></li>
    <li><a href="/users/sign_up">Criar Conta</a></li>
    <li><div class="divider"></div></li>
  <% end %>
</ul>